### ISSUE TITLE
Problem in running openedx on browser installed windows 7 

### ISSUE THREAD

**Issue by jyotichauhan** [Deeman2014/Open_edX_Windows_7_Installation#2]
Hello all,

I completed the installation of openedx fullstack on windows 7 ultimate using instruction given on http://open-edx-windows-7-installation-instructions.readthedocs.org/en/latest/8_Starting_Stopping_edX.html

Now, after successful installation, I'm not able to access LMS on 192.168.33.10 using my browser chrome as instructed in 8.5 of the instructions followed for installation
This is not loading any page.

Please suggest some solutions for the same.

**Comment by Deeman2014** [comment]
Hello,
I did not write those instructions, I wrote a different page.
Is this the one you actually followed?
Deeman2014

**Comment by jyotichauhan** [comment]
Hello,

Yes i followed the instructions from this page(https://github.com/Deeman2014/Open_edX_Windows_7_Installation)
The problem is after successful installation, browser of the host machine(win 7-on which Virtual box is running) is not able to load the LMS page.

some of the confusions are:
1) how the host machine will be able to connect with the instance of openedx which is on virtual environment?
2) is the browser also need to be on virtual environment? if so, how can we connect these two Vms?

I have tried so many things.Please help me out to solve the issue.

**Comment by Deeman2014** [comment]
Hi,
Sorry for the delay.
Yes, that is a good question, which I have solved.
Let me get my edX system up and I can respond to that.
Give me a bit.
Will get back to you.
Dee

**Comment by Deeman2014** [comment]
Okay,

Let me know what:
1) Hhardware are you using
2) Version of Windows 7 you are running
3) Version of Ubuntu you installed
4) Steps you actually performed to do the installation
5) Screenshot of how you start the system
6)  Screenshot of your virtual machine settings

Did you load the Virtual Box Extensions?
What version of Windows 7 are you using, Home, Professional, Enterprise, or
Ultimate?
Did you activate NFS?

If you can provide that, I might be able to help.

Cheers,

Derrick

**Comment by Deeman2014** [comment]
![flcx](https://cloud.githubusercontent.com/assets/8691899/9419301/80b40604-4828-11e5-94e2-76740d2e88c3.jpg)

When successfully loaded, you can load the LMS from either the Windows 7 host or if you install the Ubuntu GUI, from the local host.

Let's see about getting the Windows 7 host to work first, okay?

Derrick

**Comment by jyotichauhan** [comment]
Sytem hardware details are:
1)Windows Ultimate 
2)System type: 32 bit
3)CPU 2.20 Ghz
4)RAM- 2GB

NFS was activated before the installation.
I don't know about the virtual box extension, this is virtual box 4.3.16
Ubuntu 64 bit is running on the VBOX.

I start it as
1) select testopenedx_default instance and click start
![image](https://cloud.githubusercontent.com/assets/12845900/9419279/0258058a-4878-11e5-98c7-dad7b0e75fd2.png)

2) after showing startup of some services,it ended with the login page as precise 64 login:
![image](https://cloud.githubusercontent.com/assets/12845900/9419306/2ebafa56-4878-11e5-944e-feccc05408f8.png)

3) now if i open google chrome my default browser with http://192.168.33.10/ . it displays web page not available 
![image](https://cloud.githubusercontent.com/assets/12845900/9419400/eab420de-4878-11e5-89b1-81223a1c6a43.png)

**Comment by Deeman2014** [comment]
Okay, what variant of Windows are you running?

**Comment by Deeman2014** [comment]
Try to log in using:
ID: vagrant
Password: vagrant

Ah, and yes, that was the Installation Guide that I wrote, for Windows 7,
so you were in the right place.
Derrick

**Comment by Deeman2014** [comment]
Sorry, between phone calls,
Yes, you are using Windows 7 Ultimate. All good.
So, now, I am free, let's look at this now...
Dee

**Comment by Deeman2014** [comment]
I think you need to install the VirtualBox Extension Pack 4.3.16...the link
to it no longer works.
Let me look for the file.
Hold on.
Derrick

**Comment by jyotichauhan** [comment]
After logged in using vagrant if and password
Its not working with this
Means this id and pwd are giving access to vagrant@precise64
But on brower,still same response;web page not available

**Comment by Deeman2014** [comment]
It might be that the extension pack is not installed.

I just found a link to it here:

https://www.virtualbox.org/wiki/Download_Old_Builds_4_3_pre24

Then look for and get the Extension Pack for Windows - 4.3.16 All Versions

Here is the link to that one:

http://download.virtualbox.org/virtualbox/4.3.16/Oracle_VM_VirtualBox_Extension_Pack-4.3.16-95972.vbox-extpack

Try installing that.

It might do the trick.

Derrick

**Comment by Deeman2014** [comment]
Actually, the link to the extension pack works from the documentation as
well.
On this page:
https://github.com/Deeman2014/Open_edX_Windows_7_Installation/blob/master/2_Prerequisites.rst

**Comment by jyotichauhan** [comment]
Thanks for the quick response....i will try with the extension pack....so
using virtual box extension pack ;do i need to install openedx again, using
your instruction manual?

**Comment by Deeman2014** [comment]
No, just install the extension pack..
.I am pretty sure you need the correct version installed.

**Comment by Deeman2014** [comment]
How is it going, now?

**Comment by jyotichauhan** [comment]
Still same response from browser...web page not available...

Please suggest something

**Comment by Deeman2014** [comment]
What is your background in PC's, Windows, Ubuntu?
How programming language savvy are you?
Do you know Ubuntu?

**Comment by Deeman2014** [comment]
It might that:
1) edX is not installed properly
2) The IP address to the server is not what you entered

If you had a GUI on the Ubuntu instance, you might be able to view it using
a browser from within Ubuntu, using:
 http://localhost

But you would have to install a GUI on the server version of Ubuntu 12.04

You also need to check to see what IP the edX has been set up with.

Here is a page that shows them loading using a different IP.

http://www.dangtrinh.com/2013/07/edx-platform-up-and-running-in-vagrant.html

Also, how much reading of edX installation and configuration have you done?
Have you looked at the edX installation documents from OpenEdx?

And, what is your name?

Derrick

**Comment by jyotichauhan** [comment]
Dear Deeman,

I tried to install it from scratch after deleting and uninstalling all the files.
The instruction i followed is https://github.com/Deeman2014/Open_edX_Windows_7_Installation
Now during vagrant up ,it is showing it the error
C:\edx_birch>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cypress-fullstack' could not be found. Attempting to find and
install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'cypress-fullstack' (v0) for provider: virtualbox
    default: Downloading: http://files.edx.org/vagrant-images/cypress-fullstack.
box
    default: Progress: 100% (Rate: 983k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'cypress-fullstack' (v0) for 'virtualbox'!
==> default: Importing base box 'cypress-fullstack'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: edx_birch_default_1440337201332_82178
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--memory", "4096"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxMana
ge`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "8b655242-14df-461c-97a3-6a43ccef37cd", "--memory", "4096"
]

Stderr: VBoxManage.exe: error: Invalid RAM size: 4096 MB (must be in range [4, 3
584] MB)
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component Sessio
nMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(MemorySize)(ValueUnion.u32)" at line
558 of file VBoxManageModifyVM.cpp


Please fix this customization and try again.

I tried it on 32 bit windows 7 ultimate, 2GB RAM machine
Please help me in this.

**Comment by Deeman2014** [comment]
Hello,

First things first.
My name is Derrick, not Deeman,
What is yours?
Derrick

**Comment by jyotichauhan** [comment]
Hi,

sorry for the name confusion.
My name is Jyoti.
I'm fed up with this installation. What should i do for the error i reported (in previous comment).
Please suggest some solution

Jyoti Chauhan

**Comment by Deeman2014** [comment]
Hi Joyti,

Yes, installing edX was complicated.
It involves 24-26 technologies.
It has taken me weeks and weeks to get it done.

Here is the current problem, and requirement.

You must be very careful, and use the exact components that fit the
installation instructions.
The system is very selective.
If you use one version of, say, Ubuntu x.y.z, you have to use the exact
right Virtual Box version for it. etc.

In your more recent case, the script you shared shows "cypress".
That must be a version of edX after "birch".

I started with "kilfi', and then went to "aspen".

I have never tried "cypress".

So, you HAVE to use the right version of edX that corresponds to the
installation instructions.

Look at the vagrant file, and see what version it is trying to load.

Then you either need to make sure that you have instructions for  THAT
version, or you have to download the version that you do have instructions
for.

It is VERY specific, AND the latest version does not necessarily mean that
it will be easier to install.

In fact, many people had enormous problems getting later versions to
install.

So, you can start with kilfi or aspen, or even birch, the earliest build.

And do read the installation webpages that OpenedX provides.

Also, you never mentioned your computer skillset.

That would help in giving you some guidance.

No, it is NOT easy, or straightforward.

That is for sure.

Cheers,

Derrick
